import "./StudentDrawer.css";
import { useEffect, useState } from "react";
import { X } from "lucide-react";
import { createStudent, updateStudent } from "../../api/studentApi";
const emptyStudent = { studentId: "", firstName: "", lastName: "", email: "", phone: "", gender: "", dob: "", department: "", semester: "", section: "A", admissionYear: new Date().getFullYear(), address: "", guardianName: "", guardianPhone: "", status: "Active", attendance: 0 };
function StudentDrawer({ open, onClose, student, onSaved }) {
  const [form, setForm] = useState(emptyStudent); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setForm(student ? { ...student, dob: student.dob?.slice(0, 10) || "" } : emptyStudent); setError(""); } }, [open, student]);
  if (!open) return null;
  const change = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const payload = { ...form, semester: Number(form.semester), admissionYear: Number(form.admissionYear), attendance: Number(form.attendance) }; if (student) await updateStudent(student._id, payload); else await createStudent(payload); await onSaved(); onClose(); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to save the student."); } finally { setSaving(false); } };
  return <div className="drawer-overlay"><div className="student-drawer"><div className="drawer-header"><h2>{student ? "Edit Student" : "Add Student"}</h2><button onClick={onClose}><X size={22} /></button></div><form className="student-form" onSubmit={submit}><h3>Personal Information</h3><div className="form-grid"><input required name="firstName" value={form.firstName} onChange={change} placeholder="First name" /><input required name="lastName" value={form.lastName} onChange={change} placeholder="Last name" /><input required name="studentId" value={form.studentId} onChange={change} placeholder="Roll number" /><input required type="date" name="dob" value={form.dob} onChange={change} /><select required name="gender" value={form.gender} onChange={change}><option value="">Gender</option><option>Male</option><option>Female</option><option>Other</option></select><select name="status" value={form.status} onChange={change}><option>Active</option><option>Inactive</option></select></div><h3>Academic Details</h3><div className="form-grid"><input required name="department" value={form.department} onChange={change} placeholder="Department" /><input required min="1" max="8" type="number" name="semester" value={form.semester} onChange={change} placeholder="Semester" /><input required type="number" name="admissionYear" value={form.admissionYear} onChange={change} placeholder="Admission year" /><input name="section" value={form.section} onChange={change} placeholder="Section" /><input min="0" max="100" type="number" name="attendance" value={form.attendance} onChange={change} placeholder="Attendance %" /></div><h3>Contact Information</h3><div className="form-grid"><input required type="email" name="email" value={form.email} onChange={change} placeholder="Email" /><input required name="phone" value={form.phone} onChange={change} placeholder="Phone number" /><textarea name="address" value={form.address} onChange={change} placeholder="Address" className="address-box" /></div><h3>Guardian Details</h3><div className="form-grid"><input name="guardianName" value={form.guardianName} onChange={change} placeholder="Guardian name" /><input name="guardianPhone" value={form.guardianPhone} onChange={change} placeholder="Guardian phone" /></div>{error && <p className="form-error">{error}</p>}<div className="drawer-buttons"><button type="button" className="cancel-btn" onClick={onClose}>Cancel</button><button type="submit" className="save-btn" disabled={saving}>{saving ? "Saving..." : "Save Student"}</button></div></form></div></div>;
}
export default StudentDrawer;
